In [1]:
# 基本模块的导入
# The %... is an iPython thing, and is not part of the Python language.
# In this case we're just telling the plotting library to draw things on
# the notebook, instead of on a separate window.
%matplotlib inline
# See all the "as ..." contructs? They're just aliasing the package names.
# That way we can call methods like plt.plot() instead of matplotlib.pyplot.plot().
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
from pandas import DataFrame,Series
import time
pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set_style("darkgrid")
sns.set_context("poster")
from matplotlib.font_manager import FontProperties 
font_zh = FontProperties(fname="/Library/Fonts/华文黑体.ttf", size=14)  #size可不用指定

def format_plot(ax,title,xlabel,ylabel,save_filename = "test.png",dpi = 200):
    for label in ax.get_yticklabels():
        label.set_fontproperties(font_zh) 
    for label in ax.get_xticklabels(): 
        label.set_fontproperties(font_zh) 
    plt.xlabel(xlabel,fontproperties=font_zh)
    plt.ylabel(ylabel,fontproperties=font_zh)
    plt.title(title,fontproperties=font_zh)
    plt.legend(prop=font_zh)
    plt.savefig(save_filename, dpi = dpi)

In [2]:
# 数据库的相关配置
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

# DATABASE = {
#     'drivername': 'postgres',
#     'host': 'localhost',
#     'port': '5432',
#     'username': 'twocucao',
#     'password': '',
#     'database': 'qunshi_cpanel'
# }

DATABASE = {
    'drivername': 'mysql',
    'host': 'localhost',
    'port': '3308',
    'username': 'root',
    'password': '930721',
    'database': 'pyfetcher'
}

engine = create_engine(URL(**DATABASE))

In [3]:
df = pd.read_sql_query("SELECT * FROM dianpin_shops", engine)
df.describe()

/Users/twocucao/.virtualenvs/py3-data/lib/python3.5/site-packages/numpy/lib/function_base.py:3823: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

                 id    dianpin_id     avg_price   dianpin_num    rate_taste      rate_env  rate_service  is_finished
count  18857.000000  1.885700e+04  18857.000000   9585.000000  18772.000000  18772.000000  18772.000000      18771.0
mean    9606.189267  3.523794e+07     17.805430    134.404591      4.539335      4.504320      4.510404          1.0
std     5567.969821  2.318581e+07     41.899177    550.887567      3.509212      3.484103      3.487682          0.0
min        1.000000  5.002420e+05     -1.000000      1.000000      0.000000      0.000000      0.000000          1.0
25%     4756.000000  1.627563e+07     -1.000000           NaN           NaN           NaN           NaN          NaN
50%     9645.000000  2.528305e+07     -1.000000           NaN           NaN           NaN           NaN          NaN
75%    14428.000000  5.877531e+07     21.000000           NaN           NaN           NaN           NaN          NaN
max    19253.000000  6.923056e+07   1364.000000  15959.000000      9.300000      9.400000      9.400000          1.0

## 进行简单的统计

1. 按照人均消费进行分类.0~50,50~100,100~150,200+

In [4]:
groupd = df[['region','avg_price','dianpin_num']].groupby("region").agg(['mean', 'count'])

In [5]:
# 每个地区的数量
df.groupby("region").size()

region
七宝          1838
万源城/东兰路      675
交大闵行校区       168
仲盛商业中心        42
北桥            66
华漕           561
南方商城         782
吴泾           219
好爱广场         177
春申地区         581
浦江镇          554
老闵行         1356
莘庄          1662
莘庄龙之梦        117
虹桥镇         1145
虹梅路          508
金平路步行街        35
闵行区         7725
颛桥           224
龙柏地区         403
龙盛国际商业广场      19
dtype: int64

In [6]:
# 每个菜系数量
df.groupby("category_name").size()

category_name
SPR咖啡        6
上岛咖啡        19
东北菜        244
东南亚菜        16
两岸咖啡         4
中东菜          1
云南菜         10
其他        1411
其他中餐       628
其他江浙菜      250
其他西餐       126
农家菜        286
冰淇淋        142
创意菜         43
包子         332
北京菜         79
印度菜          4
台湾菜         73
咖啡厅          8
宁波菜         15
寿司/简餐       57
小吃        1728
小吃快餐         5
小火锅         27
小笼          55
小龙虾        175
山西菜          2
川菜          48
川菜/家常菜     574
徽菜         140
          ...
粤菜馆        101
粥店          77
素菜          22
绍兴菜          2
自助餐         63
茶餐厅         77
蟹宴           3
西北菜         62
西式甜点       203
西式简餐       107
西班牙菜         4
西餐          17
贵州菜          9
越南菜         10
迪欧咖啡         5
重庆火锅        55
锅贴          16
闽菜           7
零食         158
面包         535
面包甜点       273
面馆         708
韩国料理       421
饮品         843
饺子         203
馄饨         255
香锅         127
鱼火锅         56
鲁菜          19
麻辣烫        349
dtype: int64

In [7]:
df.groupby(["region","category_name"]).size()

region    category_name
七宝        上岛咖啡               3
          东北菜               23
          东南亚菜               1
          云南菜                3
          其他               138
          其他中餐              38
          其他江浙菜             24
          其他西餐               7
          农家菜               27
          冰淇淋               17
          创意菜                3
          包子                20
          北京菜                7
          台湾菜               12
          咖啡厅                1
          寿司/简餐              4
          小吃               198
          小火锅                5
          小笼                 8
          小龙虾               15
          川菜                 4
          川菜/家常菜            56
          徽菜                11
          快餐简餐             244
          意大利菜               1
          新疆菜                9
          日式烧烤/铁板烧           6
          日本料理              19
          星巴克                2
          更多咖啡厅             70
                          ...
龙柏地区      自助餐                1
          茶餐厅                2
          西式甜点               5
          西式简餐               2
          重庆火锅               3
          零食                 2
          面包                13
          面包甜点               4
          面馆                 6
          韩国料理              42
          饮品                21
          饺子                 3
          馄饨                 2
          香锅                 2
          鲁菜                 1
          麻辣烫                3
龙盛国际商业广场  其他中餐               1
          其他西餐               1
          农家菜                1
          快餐简餐               2
          日式烧烤/铁板烧           1
          更多咖啡厅              1
          比萨                 1
          海鲜                 2
          烤鱼                 1
          牛排                 1
          面馆                 1
          韩国料理               2
          饮品                 3
          鱼火锅                1
dtype: int64

In [8]:
## 原有数据中有部分数据为多余数据,需要被去除,满足如下要求
# 1.无评论
# 2.无人均消费

df[(df['dianpin_num'] >= 0) & (df['avg_price'] >= 0)].count()

id               5487
dianpin_id       5487
region           5487
shop_name        5487
category         5487
category_name    5487
avg_price_raw    5487
avg_price        5487
dianpin_num      5487
rate_taste       5487
rate_env         5487
rate_service     5487
address          5487
telephone        5487
task_id             0
sub_type         5411
is_finished      5487
dtype: int64

In [9]:
# 统计范围需要增加辅助列,或者直接可视化交给其他工具做.
df['status_range'] = pd.cut(df['dianpin_num'], bins=[-1, 50, 100, 200, 300,9999999], labels=False)

In [10]:
df[['region','avg_price','dianpin_num','status_range']]

        region  avg_price  dianpin_num  status_range
0          虹桥镇        283        458.0           4.0
1          虹桥镇        114        155.0           2.0
2         春申地区         72        850.0           4.0
3          老闵行         43        322.0           4.0
4          闵行区         76         99.0           1.0
5           七宝         54        136.0           2.0
6           莘庄         80        907.0           4.0
7           华漕         81       2534.0           4.0
8          虹桥镇        271        956.0           4.0
9      万源城/东兰路        111        733.0           4.0
10         老闵行         88       1151.0           4.0
11          莘庄         77          NaN           NaN
12          莘庄         74        384.0           4.0
13       莘庄龙之梦         72       4206.0           4.0
14         虹桥镇        141        797.0           4.0
15        南方商城         55        218.0           3.0
16         老闵行         70        275.0           3.0
17         闵行区         62          NaN           NaN
18          华漕         68       2827.0           4.0
19         闵行区        134        232.0           3.0
20         老闵行         86        610.0           4.0
21          莘庄         69        677.0           4.0
22          莘庄         71        300.0           3.0
23         浦江镇         96        420.0           4.0
24        南方商城        111       2967.0           4.0
25          七宝         74        734.0           4.0
26     万源城/东兰路         97       1352.0           4.0
27         浦江镇         63          NaN           NaN
28          七宝        337        163.0           2.0
29          莘庄        104       4690.0           4.0
...        ...        ...          ...           ...
18827      闵行区         -1          NaN           NaN
18828      闵行区         -1          NaN           NaN
18829      闵行区         -1          1.0           0.0
18830      闵行区         -1          1.0           0.0
18831      闵行区         -1          NaN           NaN
18832      闵行区         -1          NaN           NaN
18833      闵行区         -1          NaN           NaN
18834      闵行区         -1          NaN           NaN
18835      闵行区         -1          NaN           NaN
18836      闵行区         -1          NaN           NaN
18837  万源城/东兰路         -1          NaN           NaN
18838      闵行区         -1          NaN           NaN
18839      闵行区         -1          NaN           NaN
18840      闵行区         -1          NaN           NaN
18841      闵行区         -1          NaN           NaN
18842      闵行区         -1          NaN           NaN
18843      闵行区         -1          NaN           NaN
18844     春申地区         -1          NaN           NaN
18845       吴泾         -1          NaN           NaN
18846      闵行区         -1          NaN           NaN
18847      闵行区         -1          NaN           NaN
18848      闵行区         -1          NaN           NaN
18849      闵行区         -1          NaN           NaN
18850      闵行区         -1          NaN           NaN
18851      闵行区         -1          NaN           NaN
18852      闵行区         -1          NaN           NaN
18853      闵行区         -1          NaN           NaN
18854      闵行区         -1          NaN           NaN
18855      闵行区         -1          NaN           NaN
18856      闵行区         -1          NaN           NaN

[18857 rows x 4 columns]

In [11]:
from IPython.display import HTML
consume_unknown_restaurant_count = len(df[(df["avg_price"] == -1 )].index)
consume_0_50_restaurant_count = len(df[(df["avg_price"] >= 0 ) & (df["avg_price"] < 50 )].index)
consume_50_100_restaurant_count = len(df[(df["avg_price"] >= 50 ) & (df["avg_price"] < 100 )].index)
consume_100_150_restaurant_count = len(df[(df["avg_price"] >= 100 ) & (df["avg_price"] < 150 )].index)
consume_150_200_restaurant_count = len(df[(df["avg_price"] >= 150 ) & (df["avg_price"] < 200 )].index)
consume_200_greater_restaurant_count = len(df[(df["avg_price"] >= 200 )].index)

In [12]:
chart_header_html = """
<div id="chart" style="width:800px; height:600px;"></div>
<script>
    require.config({
         paths:{
            echarts: '//cdn.bootcss.com/echarts/3.2.3/echarts.min',
         }
    });
    require(['echarts'],function(ec){
var myChart = ec.init(document.getElementById('chart'));
                var option = {
                    title: {
                        text: '闵行区美食类人均消费餐馆分布',
                        subtext: '数据来自大众点评',
                        x: 'center'
                    },
                    tooltip: {
                        trigger: 'item',
                        formatter: "{a} <br/>{b} : {c} ({d}%)"
                    },
                    legend: {
                        orient: 'vertical',
                        left: 'left',
                        data: ['人均消费不明','人均消费0~50元', '人均消费50~100元', '人均消费100~150元', '人均消费150~200元', '人均消费200元以上']
                    },
                    series: [
                        {
                            name: '店铺比例',
                            type: 'pie',
                            radius: '55%',
                            center: ['50%', '60%'],
                            data: [


""" 
chart_content_html = """
                                {value: %s, name: '人均消费不明'},
                                {value: %s, name: '人均消费0~50元'},
                                {value: %s, name: '人均消费50~100元'},
                                {value: %s, name: '人均消费100~150元'},
                                {value: %s, name: '人均消费150~200元'},
                                {value: %s, name: '人均消费200元以上'}
""" % (consume_unknown_restaurant_count,consume_0_50_restaurant_count,consume_50_100_restaurant_count,consume_100_150_restaurant_count,consume_150_200_restaurant_count,consume_200_greater_restaurant_count)
chart_footer_html = """
                            ],
                            itemStyle: {
                                emphasis: {
                                    shadowBlur: 10,
                                    shadowOffsetX: 0,
                                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                                }
                            }
                        }
                    ]
                };
                myChart.setOption(option);
    });
</script>
"""
HTML(
 chart_header_html + chart_content_html + chart_footer_html
)

In [13]:
df.to_excel("大众点评闵行区美食餐厅简单统计.xlsx")